name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Build app
    runs-on: windows-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: x86
      
      - name: Install requirements
        run: pip install -U pyinstaller

      - name: Install required libraries
        run: pip install -r requirements.txt

      - name: Compile script
        run: python compile.py

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'mansuf/mangadex-downloader-binary-files-test'
        run: |
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Cleanup build
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'mansuf/mangadex-downloader-binary-files-test'
        run: |
          copy "dist\mangadex-dl-win32.exe" "mangadex-dl-win32-${{ env.VERSION_TAG }}"

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'mansuf/mangadex-downloader-binary-files-test'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: mangadex-downloader ${{ env.VERSION_TAG }}
          files: mangadex-dl-win32-${{ env.VERSION_TAG }}
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
