name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Build app
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.5', '3.6', '3.7', '3.8', '3.9', '3.10' ]

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x86

      - name: Install required libraries
        run: |
          pip install -U wheel pyinstaller
          pip install -r requirements.txt

      - name: Test import module
        run: |
          python -c "import mangadex_downloader"

      - name: Get python version
        run: |
          $PythonVersion = (python --version)
          echo "python_version=${PythonVersion}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Compile script
        if: ${{ env.python_version == '3.10' }}
        run: py -3.10 compile.py

      - name: Cleanup build
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'mansuf/mangadex-downloader-binary-files-test'
        run: |
          copy "dist\mangadex-dl-win32.exe" "mangadex-dl_win32_${{ github.ref_name }}.exe"

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'mansuf/mangadex-downloader-binary-files-test'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.GIRHUB_REF_NAME }}
          name: mangadex-downloader ${{ github.ref_name }}
          files: |
            mangadex-dl_win32_${{ github.ref_name }}.exe
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

